### ISSUE TITLE
Solana CCTP support EPIC

### ISSUE THREAD

**Issue by boojamya** [noble-assets/noble-cctp-relayer#60]
This is the epic needed for Solana CCTP support in the Relayer

CCTP Docs: https://developers.circle.com/stablecoins/docs/cctp-getting-started

```[tasklist]
### Tasks
- [ ] https://github.com/strangelove-ventures/noble-cctp-relayer/issues/61
- [ ] https://github.com/strangelove-ventures/noble-cctp-relayer/issues/62
- [ ] https://github.com/strangelove-ventures/noble-cctp-relayer/issues/63
- [ ] https://github.com/strangelove-ventures/noble-cctp-relayer/issues/64
- [ ] https://github.com/strangelove-ventures/noble-cctp-relayer/issues/65
- [ ] https://github.com/strangelove-ventures/noble-cctp-relayer/issues/66
```

**Comment by jonathanpberger** [comment]
Blocked pending Jelena letting us know if they still want to do this.
